### ISSUE TITLE
Build issue on Rocky Linux 9 aarch64

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/hardened_malloc#228]
clang-15: error: argument unused during compilation: '-fstack-clash-protection' [-Werror,-Wunused-command-line-argument]

Need to look into this

**Comment by flawedworld** [comment]
Need to just disable this on non-x86_64

**Comment by flawedworld** [comment]
https://bugs.llvm.org/show_bug.cgi?id=40802

**Comment by thestinger** [comment]
Fixed.

**Comment by flawedworld** [comment]
Still persistent. I think this just needs to be special cased for arm64.
